# Generated by Django 4.1.6 on 2023-03-07 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorme', '0003_auto_20230226_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('Tutor', 'Tutor'), ('Tutee', 'Tutee'), ('Not_Decided', 'Not Decided')], default='Not_Decided', max_length=11)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('about_me', models.CharField(default='', max_length=500)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=50)),
                ('hourly_fee', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('online', models.BooleanField(default=False)),
                ('contact_info', models.CharField(max_length=150)),
                ('comments', models.CharField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorme.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutee',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
