# Generated by Django 4.1.6 on 2023-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0005_alter_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
    ]
