# Generated by Django 4.1.6 on 2023-03-09 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0006_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='classes',
            name='section_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='units',
            field=models.IntegerField(default=3),
        ),
    ]
