# Generated by Django 4.1.6 on 2023-03-11 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0008_alter_classes_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
