# Generated by Django 4.1.6 on 2023-03-11 04:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0009_classes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='class_title',
        ),
        migrations.AddField(
            model_name='post',
            name='classes',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='tutorme.classes'),
            preserve_default=False,
        ),
    ]
