# Generated by Django 4.1.7 on 2023-03-19 02:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0011_person_booked_sessions_post_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='capacity',
            new_name='max_capacity',
        ),
        migrations.AddField(
            model_name='post',
            name='enrolled_tutees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='session_range_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='session_range_start',
            field=models.DateTimeField(null=True),
        ),
    ]
