# Generated by Django 4.1.7 on 2023-03-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0012_rename_capacity_post_max_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='session_range_end',
            new_name='sessionRangeEnd',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='session_range_start',
            new_name='sessionRangeStart',
        ),
        migrations.RemoveField(
            model_name='person',
            name='booked_sessions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='enrolled_tutees',
        ),
        migrations.RemoveField(
            model_name='post',
            name='person',
        ),
        migrations.AddField(
            model_name='post',
            name='creatorEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='enrolled_tutee',
            field=models.ManyToManyField(to='tutorme.person'),
        ),
    ]
