# Generated by Django 4.1.7 on 2023-03-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0013_rename_session_range_end_post_sessionrangeend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creatorName',
            field=models.CharField(default='', max_length=500),
        ),
    ]
