# Generated by Django 4.1.7 on 2023-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0015_post_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
