# Generated by Django 4.1.7 on 2023-03-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0017_session_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_request',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='session_request',
            name='tutor_message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
