# Generated by Django 4.1.6 on 2023-04-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0018_session_request_status_session_request_tutor_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creatorEmail', models.EmailField(max_length=254, null=True)),
                ('recipientEmail', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='session_request',
            name='sessionEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session_request',
            name='sessionStart',
            field=models.DateTimeField(null=True),
        ),
    ]
