# Generated by Django 3.2.17 on 2023-05-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0019_notification_session_request_sessionend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='hourly_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
